// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertsController from "./alerts_controller"
application.register("alerts", AlertsController)

import ApplicationController from "./application_controller"
application.register("application", ApplicationController)

import AvatarController from "./avatar_controller"
application.register("avatar", AvatarController)

import ContextMenuController from "./context_menu_controller"
application.register("context-menu", ContextMenuController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NoteController from "./note_controller"
application.register("note", NoteController)
